### ISSUE TITLE
Broken code when "go getting" talkkonnect.

### ISSUE THREAD

**Issue by henrickveloso** [talkkonnect/gopus#1]
I´ve tried to "go get" talkkonnect today, after your last commit, and I ve got the following error:

~/gocode/src$ go get github.com/talkkonnect/talkkonnect/
\# github.com/talkkonnect/gopus
In file included from ./opus-1.3.1/silk/SigProc_FIX.h:51,
                 from ./opus-1.3.1/silk/main.h:31,
                 from ./opus-1.3.1/silk/CNG.c:32,
                 from github.com/talkkonnect/gopus/opus_nonshared.go:11:
./opus-1.3.1/silk/arm/biquad_alt_arm.h:31:11: fatal error: celt/arm/armcpu.h: No such file or directory
 \# include "celt/arm/armcpu.h"
           ^~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by zrdimetc** [comment]
Were you building on ARM or x86_64 architecture? Compatibility to x86_64 systems was sacrificed because of upgrading opus 1.1.2 to 1.3.1. Use the initial commit of [gopus](https://github.com/talkkonnect/gopus/tree/5477933d774f486cd6d5d0441ec434eadbf0986e) .
